apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  expression: /m/type/lab
  version: 1.0.0
  description: IMDb App

resources:
  - service.yaml
  - ingress.yaml
  - deployment.yaml

images:
- name: ghcr.io/cse-labs/imdb
  newTag: 1.0.0
