apiVersion: goa.com/v1
kind: Application
metadata:
  name: heartbeat
spec:
  namespace: heartbeat
  description: Heartbeat
  metadata:
    type: add-on
    dependsOn: cert-manager
  versions:
    - version: "0.1.0"
      namespace: heartbeat
      path: apps/heartbeat/base
      expression: /c/*
      metadata:
        imageTag: 0.1.0
    - version: "0.4.0"
      namespace: heartbeat
      path: apps/heartbeat/overlays/v0.4.0
      expression: /g/ring0
      metadata:
        imageTag: 0.4.0

---

apiVersion: goa.com/v1
kind: Application
metadata:
  name: cert-manager
spec:
  namespace: cert-manager
  description: Cert Manager
  metadata:
    type: add-on
  versions:
    - version: "1.14.4"
      namespace: cert-manager
      path: apps/cert-manager/base
      expression: /c/*
      metadata:
        imageTag: 1.14.4

---

# apiVersion: goa.com/v1
# kind: Application
# metadata:
#   name: make-line
# spec:
#   description: Make Line
#   metadata:
#     type: application
#   versions:
#     - version: "0.1.0"
#       path: apps/make-line/base
#       expression: /c/*
#       metadata:
#         imageTag: 0.1.0
# ---
# apiVersion: goa.com/v1
# kind: Application
# metadata:
#   name: ingress-nginx
# spec:
#   description: Ingress NGINX
#   metadata:
#     type: add-on
#     dependsOn: cert-manager
#   versions:
#     - version: "4.10.1"
#       path: apps/ingress-nginx/base
#       expression: /c/*
#       metadata:
#         imageTag: 4.10.1
# ---
# apiVersion: goa.com/v1
# kind: Application
# metadata:
#   name: pos
# spec:
#   description: POS
#   metadata:
#     type: application
#   versions:
#     - version: "0.1.0"
#       path: apps/pos/base
#       expression: /c/*
#       metadata:
#         imageTag: 0.1.0
