apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  expression: /m/type/lab
  version: 1.1.0
  description: IMDb App

resources:
- ../../base

images:
- name: ghcr.io/cse-labs/imdb
  newTag: 1.1.0
